import type {
  Appointment,
  Customer,
  FollowUpTask,
  Organization,
  Provider,
  StaffMember,
  Service,
  VisitReport,
} from "@/lib/domain";

export const organization: Organization = {
  id: "org-koi-dental",
  name: "Koi Dental Coordination Center",
  businessType: "dental_clinic",
  email: "ops@koi-dental.local",
  phone: "+977 01-4420000",
  address: "Baluwatar, Kathmandu",
  timezone: "Asia/Kathmandu",
  primaryCalendar: "AD",
  businessDayStartsAt: "08:00",
  businessDayEndsAt: "18:00",
  defaultBufferMinutes: 10,
  reminderLeadMinutes: 1440,
  allowOverlaps: false,
};

const defaultAvailability = (providerId: string) =>
  [0, 1, 2, 3, 4, 5].map((dayOfWeek) => ({
    id: `${providerId}-availability-${dayOfWeek}`,
    providerId,
    locationId: "location-main-kathmandu",
    dayOfWeek,
    startsAtLocal: "08:00",
    endsAtLocal: "18:00",
    slotDurationMinutes: 30,
    bufferMinutes: 0,
    isActive: true,
  }));

const defaultBlockedTimes = (providerId: string) => [
  {
    id: `${providerId}-block-lunch`,
    providerId,
    locationId: "location-main-kathmandu",
    startsAtIso: "2026-05-06T06:15:00.000Z",
    endsAtIso: "2026-05-06T07:00:00.000Z",
    reason: "Lunch break",
  },
];

const defaultRecurringBlocks = (providerId: string) => [
  {
    id: `${providerId}-recurring-break-mon`,
    providerId,
    locationId: "location-main-kathmandu",
    dayOfWeek: 1,
    startsAtLocal: "13:00",
    endsAtLocal: "14:00",
    reason: "Midday break",
    isActive: true,
  },
];

const defaultServiceIds = [
  "service-checkup",
  "service-cleaning",
  "service-root-canal",
  "service-extraction",
  "service-ortho-review",
];

export const providers: Provider[] = [
  {
    id: "provider-arya",
    userId: "user-arya",
    name: "Dr. Arya Shrestha",
    roleLabel: "Doctor",
    specialty: "Restorative dentistry",
    color: "#0f766e",
    capacityMinutes: 420,
    bookedMinutes: 365,
    status: "Busy",
    availability: defaultAvailability("provider-arya"),
    recurringBlocks: defaultRecurringBlocks("provider-arya"),
    blockedTimes: defaultBlockedTimes("provider-arya"),
    serviceIds: defaultServiceIds,
  },
  {
    id: "provider-mira",
    userId: "user-mira",
    name: "Dr. Mira KC",
    roleLabel: "Doctor",
    specialty: "Orthodontics",
    color: "#7c3aed",
    capacityMinutes: 420,
    bookedMinutes: 285,
    status: "Available",
    availability: defaultAvailability("provider-mira"),
    recurringBlocks: defaultRecurringBlocks("provider-mira"),
    blockedTimes: defaultBlockedTimes("provider-mira"),
    serviceIds: defaultServiceIds,
  },
  {
    id: "provider-nabin",
    userId: "user-nabin",
    name: "Dr. Nabin Rai",
    roleLabel: "Doctor",
    specialty: "Oral surgery",
    color: "#b45309",
    capacityMinutes: 360,
    bookedMinutes: 340,
    status: "Busy",
    availability: defaultAvailability("provider-nabin"),
    recurringBlocks: defaultRecurringBlocks("provider-nabin"),
    blockedTimes: defaultBlockedTimes("provider-nabin"),
    serviceIds: defaultServiceIds,
  },
  {
    id: "provider-sana",
    userId: "user-sana",
    name: "Sana Maharjan",
    roleLabel: "Hygienist",
    specialty: "Preventive care",
    color: "#2563eb",
    capacityMinutes: 360,
    bookedMinutes: 210,
    status: "Available",
    availability: defaultAvailability("provider-sana"),
    recurringBlocks: defaultRecurringBlocks("provider-sana"),
    blockedTimes: defaultBlockedTimes("provider-sana"),
    serviceIds: defaultServiceIds,
  },
];

export const staff: StaffMember[] = [
  {
    id: "user-owner",
    organizationId: organization.id,
    name: "Darrell Steward",
    email: "owner@zendenta.local",
    phone: "+977 980-000-1100",
    role: "Owner",
    staffLabel: "Clinic owner",
    department: "Operations",
    employeeCode: "OWN-001",
    employmentType: "Full time",
    startDateIso: "2024-01-15T00:00:00.000Z",
    emergencyContactName: "Nora Steward",
    emergencyContactPhone: "+977 980-000-1101",
    notes: "Primary signatory and operations owner.",
    status: "Active",
    isSchedulable: false,
  },
  {
    id: "user-reception",
    organizationId: organization.id,
    name: "Reception Desk",
    email: "receptionist@zendenta.local",
    phone: "+977 980-100-2200",
    role: "Receptionist",
    staffLabel: "Front desk",
    department: "Reception",
    employeeCode: "REC-014",
    employmentType: "Full time",
    startDateIso: "2025-06-01T00:00:00.000Z",
    emergencyContactName: "Sujan Khadka",
    emergencyContactPhone: "+977 980-100-2201",
    notes: "Handles confirmations, intake, and same-day reshuffles.",
    status: "Active",
    isSchedulable: false,
  },
  {
    id: "user-arya",
    organizationId: organization.id,
    providerId: "provider-arya",
    name: "Dr. Arya Shrestha",
    email: "arya@zendenta.local",
    phone: "+977 980-201-0001",
    role: "Provider",
    staffLabel: "Doctor",
    department: "Restorative",
    employeeCode: "DOC-101",
    licenseNumber: "NMC-DEN-20341",
    employmentType: "Full time",
    startDateIso: "2023-04-10T00:00:00.000Z",
    emergencyContactName: "Isha Shrestha",
    emergencyContactPhone: "+977 980-201-0011",
    notes: "Takes higher-complexity restorative sessions.",
    status: "Active",
    isSchedulable: true,
    provider: providers[0],
    lastLoginAtIso: "2026-05-14T10:25:00.000Z",
  },
  {
    id: "user-mira",
    organizationId: organization.id,
    providerId: "provider-mira",
    name: "Dr. Mira KC",
    email: "mira@zendenta.local",
    phone: "+977 980-201-0002",
    role: "Provider",
    staffLabel: "Orthodontist",
    department: "Orthodontics",
    employeeCode: "DOC-115",
    licenseNumber: "NMC-DEN-22140",
    employmentType: "Full time",
    startDateIso: "2024-02-12T00:00:00.000Z",
    emergencyContactName: "Sarina KC",
    emergencyContactPhone: "+977 980-201-0012",
    notes: "Owns continuity-sensitive aligner and braces follow-up.",
    status: "Active",
    isSchedulable: true,
    provider: providers[1],
    lastLoginAtIso: "2026-05-15T03:20:00.000Z",
  },
  {
    id: "user-nabin",
    organizationId: organization.id,
    providerId: "provider-nabin",
    name: "Dr. Nabin Rai",
    email: "nabin@zendenta.local",
    phone: "+977 980-201-0003",
    role: "Provider",
    staffLabel: "Oral surgeon",
    department: "Surgery",
    employeeCode: "DOC-124",
    licenseNumber: "NMC-DEN-21402",
    employmentType: "Part time",
    startDateIso: "2024-08-01T00:00:00.000Z",
    emergencyContactName: "Mona Rai",
    emergencyContactPhone: "+977 980-201-0013",
    notes: "Scheduled for procedure blocks and higher-acuity consults.",
    status: "Active",
    isSchedulable: true,
    provider: providers[2],
    lastLoginAtIso: "2026-05-13T12:00:00.000Z",
  },
  {
    id: "user-sana",
    organizationId: organization.id,
    providerId: "provider-sana",
    name: "Sana Maharjan",
    email: "sana@zendenta.local",
    phone: "+977 980-201-0004",
    role: "Assistant",
    staffLabel: "Dental hygienist",
    department: "Preventive care",
    employeeCode: "CLN-205",
    licenseNumber: "NDHA-7741",
    employmentType: "Full time",
    startDateIso: "2025-01-10T00:00:00.000Z",
    emergencyContactName: "Rekha Maharjan",
    emergencyContactPhone: "+977 980-201-0014",
    notes: "Supports hygiene pipeline and preventive continuity.",
    status: "Active",
    isSchedulable: true,
    provider: providers[3],
    lastLoginAtIso: "2026-05-12T08:40:00.000Z",
  },
];

export const customers: Customer[] = [
  {
    id: "customer-lhamu",
    name: "Lhamu Sherpa",
    patientCode: "KD-2401",
    phone: "+977 980-110-4570",
    email: "lhamu.sherpa@email.com",
    age: 34,
    gender: "Female",
    address: "Maharajgunj, Kathmandu",
    dateOfBirthIso: "1992-02-12T00:00:00.000Z",
    emergencyContactName: "Passang Sherpa",
    emergencyContactPhone: "+977 980-100-0001",
    allergies: "No known drug allergies",
    medicalNotes: "Crown planning pending after root canal completion.",
    status: "Active",
    risk: "Needs attention",
    lastVisitIso: "2026-02-13T10:30:00+05:45",
    dentalChart: {
      id: "chart-customer-lhamu",
      chartData: { segments: ["16", "17"], notes: ["Crown planning pending"] },
      version: 2,
      updatedAtIso: "2026-05-06T10:05:00+05:45",
    },
  },
  {
    id: "customer-bibek",
    name: "Bibek Adhikari",
    patientCode: "KD-2402",
    phone: "+977 981-442-0198",
    email: "bibek.a@email.com",
    age: 41,
    gender: "Male",
    address: "Lalitpur, Bagmati",
    dateOfBirthIso: "1985-09-22T00:00:00.000Z",
    emergencyContactName: "Mina Adhikari",
    emergencyContactPhone: "+977 981-300-4004",
    allergies: "No known allergies",
    medicalNotes: "Prefers preventive appointments after 3 PM.",
    status: "Active",
    risk: "Routine",
    lastVisitIso: "2026-04-02T15:45:00+05:45",
  },
  {
    id: "customer-srijana",
    name: "Srijana Tamang",
    patientCode: "KD-2403",
    phone: "+977 984-218-6671",
    email: "srijana.tamang@email.com",
    age: 27,
    gender: "Female",
    address: "Bhaktapur, Bagmati",
    dateOfBirthIso: "1999-01-18T00:00:00.000Z",
    emergencyContactName: "Ramesh Tamang",
    emergencyContactPhone: "+977 984-000-1122",
    allergies: "Penicillin",
    medicalNotes: "Impacted molar case with consent already on file.",
    status: "Monitoring",
    risk: "High priority",
    lastVisitIso: "2026-05-01T12:15:00+05:45",
  },
  {
    id: "customer-amit",
    name: "Amit Gurung",
    patientCode: "KD-2404",
    phone: "+977 986-009-7721",
    email: "amit.gurung@email.com",
    age: 52,
    gender: "Male",
    address: "Pokhara, Gandaki",
    dateOfBirthIso: "1974-06-09T00:00:00.000Z",
    emergencyContactName: "Sarita Gurung",
    emergencyContactPhone: "+977 986-001-8877",
    allergies: "Latex sensitivity",
    medicalNotes: "Orthodontic continuity at risk due to repeated missed reviews.",
    status: "Monitoring",
    risk: "Needs attention",
    lastVisitIso: "2025-11-28T09:00:00+05:45",
    dentalChart: {
      id: "chart-customer-amit",
      chartData: { segments: ["11", "12"], notes: ["Continuity risk flagged"] },
      version: 1,
      updatedAtIso: "2026-05-05T15:20:00+05:45",
    },
  },
  {
    id: "customer-nisha",
    name: "Nisha Basnet",
    patientCode: "KD-2405",
    phone: "+977 980-658-2401",
    email: "nisha.basnet@email.com",
    age: 19,
    gender: "Female",
    address: "Baneshwor, Kathmandu",
    dateOfBirthIso: "2007-04-03T00:00:00.000Z",
    emergencyContactName: "Sushma Basnet",
    emergencyContactPhone: "+977 980-777-2525",
    allergies: "No known allergies",
    medicalNotes: "Guardian requests printed school notes after each ortho visit.",
    status: "Active",
    risk: "Routine",
    lastVisitIso: "2026-03-17T16:45:00+05:45",
  },
  {
    id: "customer-roshan",
    name: "Roshan Thapa",
    patientCode: "KD-2406",
    phone: "+977 981-741-8839",
    email: "roshan.t@email.com",
    age: 46,
    gender: "Male",
    address: "Kirtipur, Kathmandu",
    dateOfBirthIso: "1980-12-28T00:00:00.000Z",
    emergencyContactName: "Anita Thapa",
    emergencyContactPhone: "+977 981-122-7788",
    allergies: "Metformin timing note before treatment",
    medicalNotes: "Diabetic patient; watch gum bleeding and healing response.",
    status: "Monitoring",
    risk: "High priority",
    lastVisitIso: "2026-04-25T13:10:00+05:45",
  },
];

export const visitReports: VisitReport[] = [
  {
    id: "visit-1001",
    appointmentId: "appt-1001",
    customerId: "customer-lhamu",
    providerId: "provider-arya",
    serviceId: "service-root-canal",
    appointmentStartsAtIso: "2026-05-06T08:30:00+05:45",
    createdAtIso: "2026-05-06T10:05:00+05:45",
    updatedAtIso: "2026-05-06T10:05:00+05:45",
    visitSummary: "Root canal second sitting completed with improved pain response.",
    symptoms: "Reduced night pain, mild bite sensitivity.",
    clinicalNotes: "Canal cleaned and dressed. Temporary restoration intact.",
    doctorNotes: "Plan crown preparation after symptom-free review.",
    followUpRequired: true,
    followUpDateIso: "2026-05-13T09:30:00+05:45",
    dentalChartUpdated: true,
    chartNote: "Updated root canal and temporary restoration status.",
    dentalChartRevision: {
      id: "chart-revision-1001",
      chartData: { segments: ["16", "17"], notes: ["Temporary restoration intact"] },
      note: "Post root canal update",
      createdAtIso: "2026-05-06T10:05:00+05:45",
    },
  },
  {
    id: "visit-1002",
    appointmentId: "appt-1005",
    customerId: "customer-nisha",
    providerId: "provider-mira",
    serviceId: "service-ortho-review",
    appointmentStartsAtIso: "2026-05-06T13:15:00+05:45",
    createdAtIso: "2026-05-06T14:05:00+05:45",
    updatedAtIso: "2026-05-06T14:05:00+05:45",
    visitSummary: "Bracket adjustment completed for upper arch with no breakages.",
    symptoms: "Occasional cheek irritation on upper right.",
    clinicalNotes: "Adjusted wire tension and wax guidance provided.",
    doctorNotes: "Next review can stay on routine four-week cycle.",
    followUpRequired: false,
    dentalChartUpdated: false,
  },
  {
    id: "visit-1003",
    appointmentId: "appt-1007",
    customerId: "customer-amit",
    providerId: "provider-mira",
    serviceId: "service-ortho-review",
    appointmentStartsAtIso: "2026-05-05T14:30:00+05:45",
    createdAtIso: "2026-05-05T15:20:00+05:45",
    updatedAtIso: "2026-05-05T15:20:00+05:45",
    visitSummary: "Visit marked as no-show after protected continuation slot expired.",
    symptoms: "No clinical assessment completed.",
    clinicalNotes: "Treatment continuity risk increased; aligner compliance unknown.",
    doctorNotes: "Escalate with call and offer two recovery slots within the week.",
    followUpRequired: true,
    followUpDateIso: "2026-05-07T11:00:00+05:45",
    dentalChartUpdated: false,
  },
];

export const services: Service[] = [
  {
    id: "service-checkup",
    name: "Comprehensive checkup",
    durationMinutes: 30,
    bufferMinutes: 5,
    category: "Diagnostic",
  },
  {
    id: "service-cleaning",
    name: "Scaling and polish",
    durationMinutes: 45,
    bufferMinutes: 10,
    category: "Preventive",
  },
  {
    id: "service-root-canal",
    name: "Root canal treatment",
    durationMinutes: 90,
    bufferMinutes: 15,
    category: "Treatment",
  },
  {
    id: "service-extraction",
    name: "Surgical extraction",
    durationMinutes: 75,
    bufferMinutes: 15,
    category: "Surgery",
  },
  {
    id: "service-ortho-review",
    name: "Orthodontic review",
    durationMinutes: 40,
    bufferMinutes: 5,
    category: "Orthodontics",
  },
];

export const appointments: Appointment[] = [
  {
    id: "appt-1001",
    organizationId: organization.id,
    customerId: "customer-lhamu",
    providerId: "provider-arya",
    serviceIds: ["service-root-canal"],
    startsAtIso: "2026-05-06T08:30:00+05:45",
    durationMinutes: 90,
    bufferMinutes: 15,
    status: "Confirmed",
    priority: "High",
    chair: "Chair 2",
    notes: "Second sitting. Review pain level before anesthesia.",
    communicationState: "Confirmed by phone",
  },
  {
    id: "appt-1002",
    organizationId: organization.id,
    customerId: "customer-bibek",
    providerId: "provider-sana",
    serviceIds: ["service-cleaning"],
    startsAtIso: "2026-05-06T09:15:00+05:45",
    durationMinutes: 45,
    bufferMinutes: 10,
    status: "Scheduled",
    priority: "Normal",
    chair: "Chair 4",
    notes: "Routine cleaning. Offer six-month recall setup.",
    communicationState: "SMS sent",
  },
  {
    id: "appt-1003",
    organizationId: organization.id,
    customerId: "customer-srijana",
    providerId: "provider-nabin",
    serviceIds: ["service-extraction"],
    startsAtIso: "2026-05-06T10:00:00+05:45",
    durationMinutes: 75,
    bufferMinutes: 15,
    status: "CheckedIn",
    priority: "Urgent",
    chair: "Surgery room",
    notes: "Impacted molar. Consent form completed at front desk.",
    communicationState: "Confirmed by phone",
  },
  {
    id: "appt-1004",
    organizationId: organization.id,
    customerId: "customer-amit",
    providerId: "provider-mira",
    serviceIds: ["service-ortho-review"],
    startsAtIso: "2026-05-06T11:30:00+05:45",
    durationMinutes: 40,
    bufferMinutes: 5,
    status: "FollowUpRequired",
    priority: "High",
    chair: "Chair 1",
    notes: "Missed aligner review twice. Needs treatment continuity call.",
    communicationState: "Needs call",
  },
  {
    id: "appt-1005",
    organizationId: organization.id,
    customerId: "customer-nisha",
    providerId: "provider-mira",
    serviceIds: ["service-ortho-review"],
    startsAtIso: "2026-05-06T13:15:00+05:45",
    durationMinutes: 40,
    bufferMinutes: 5,
    status: "Confirmed",
    priority: "Normal",
    chair: "Chair 1",
    notes: "Bracket adjustment. Parent requested school note.",
    communicationState: "Confirmed by phone",
  },
  {
    id: "appt-1006",
    organizationId: organization.id,
    customerId: "customer-roshan",
    providerId: "provider-arya",
    serviceIds: ["service-checkup", "service-cleaning"],
    startsAtIso: "2026-05-06T15:00:00+05:45",
    durationMinutes: 75,
    bufferMinutes: 10,
    status: "Scheduled",
    priority: "High",
    chair: "Chair 2",
    notes: "Diabetic patient. Flag gum bleeding history.",
    communicationState: "Unconfirmed",
  },
  {
    id: "appt-1007",
    organizationId: organization.id,
    customerId: "customer-amit",
    providerId: "provider-mira",
    serviceIds: ["service-ortho-review"],
    startsAtIso: "2026-05-05T14:30:00+05:45",
    durationMinutes: 40,
    bufferMinutes: 5,
    status: "NoShow",
    priority: "Urgent",
    chair: "Chair 1",
    notes: "Third missed continuation review. Escalate before archiving plan.",
    communicationState: "Needs call",
  },
];

export const followUps: FollowUpTask[] = [
  {
    id: "task-501",
    appointmentId: "appt-1007",
    customerId: "customer-amit",
    ownerId: "provider-mira",
    type: "NoShowRecovery",
    status: "Open",
    priority: "Urgent",
    dueIso: "2026-05-06T09:00:00+05:45",
    summary: "Recover missed orthodontic continuation",
    nextAction: "Call, offer two protected slots, document barrier.",
  },
  {
    id: "task-502",
    appointmentId: "appt-1006",
    customerId: "customer-roshan",
    ownerId: "provider-arya",
    type: "Reminder",
    status: "Open",
    priority: "High",
    dueIso: "2026-05-06T11:00:00+05:45",
    summary: "Confirm afternoon high-priority checkup",
    nextAction: "Phone confirmation and medication reminder.",
  },
  {
    id: "task-503",
    customerId: "customer-lhamu",
    ownerId: "provider-arya",
    type: "TreatmentContinuation",
    status: "Waiting",
    priority: "High",
    dueIso: "2026-05-07T10:00:00+05:45",
    summary: "Schedule crown planning after RCT",
    nextAction: "Create treatment plan task after today's outcome.",
  },
  {
    id: "task-504",
    customerId: "customer-bibek",
    ownerId: "provider-sana",
    type: "Recall",
    status: "InProgress",
    priority: "Normal",
    dueIso: "2026-05-08T15:00:00+05:45",
    summary: "Set six-month preventive recall",
    nextAction: "Confirm preferred weekday and create recurrence.",
  },
];
